env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - go mod download
builds:
  -
    id: "sku"
    main: ./cmd/sku/sku.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
  -
    id: "sandstorm_plugin"
    main: plugin/sandstorm/sandstorm_plugin.go
    flags: -buildmode=plugin
    binary: "sku_plugins/sandstorm.so"
    goos:
      - darwin
    goarch:
      - amd64
      - arm
      - arm64

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  -
    name: sku

    tap:
      owner: sandstorm
      name: homebrew-tap

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Sandstorm Release Bot
      email: release-bot@sandstorm.de

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/sandstorm/sku"

    # Your app's description.
    # Default is empty.
    description: "Sandstorm Kubernetes Tools"
    install: |
      libexec.install Dir["*"]
      bin.write_exec_script libexec/"sku"